package com.apon.day8;

public class Day8Input {
    public final static String EXAMPLE_INPUT = "nop +0\n" +
            "acc +1\n" +
            "jmp +4\n" +
            "acc +3\n" +
            "jmp -3\n" +
            "acc -99\n" +
            "acc +1\n" +
            "jmp -4\n" +
            "acc +6";

    public final static String INPUT = "acc +9\n" +
            "acc -2\n" +
            "acc -12\n" +
            "acc +33\n" +
            "jmp +301\n" +
            "nop +508\n" +
            "jmp +216\n" +
            "acc +27\n" +
            "acc +35\n" +
            "acc +43\n" +
            "acc +31\n" +
            "jmp +309\n" +
            "acc +18\n" +
            "acc -19\n" +
            "acc +7\n" +
            "jmp +44\n" +
            "acc -13\n" +
            "acc -17\n" +
            "acc +31\n" +
            "jmp +311\n" +
            "nop +612\n" +
            "jmp +143\n" +
            "acc +22\n" +
            "nop +85\n" +
            "jmp +458\n" +
            "acc -3\n" +
            "jmp +13\n" +
            "acc -19\n" +
            "acc +27\n" +
            "acc +12\n" +
            "jmp +483\n" +
            "acc +40\n" +
            "acc +6\n" +
            "jmp +128\n" +
            "jmp +10\n" +
            "acc +0\n" +
            "acc -3\n" +
            "acc -2\n" +
            "jmp -11\n" +
            "acc +43\n" +
            "acc -12\n" +
            "jmp +158\n" +
            "acc +0\n" +
            "jmp +240\n" +
            "jmp +1\n" +
            "acc +5\n" +
            "acc +15\n" +
            "jmp +187\n" +
            "nop +563\n" +
            "jmp +51\n" +
            "acc -16\n" +
            "jmp +158\n" +
            "jmp +322\n" +
            "acc +47\n" +
            "nop -1\n" +
            "jmp +299\n" +
            "acc +26\n" +
            "acc +25\n" +
            "jmp +232\n" +
            "jmp -9\n" +
            "acc +15\n" +
            "jmp +54\n" +
            "jmp +558\n" +
            "acc +7\n" +
            "acc -7\n" +
            "jmp +399\n" +
            "nop +447\n" +
            "jmp +71\n" +
            "acc +26\n" +
            "acc +46\n" +
            "jmp +145\n" +
            "acc +38\n" +
            "acc +30\n" +
            "acc +21\n" +
            "jmp +263\n" +
            "acc +10\n" +
            "jmp +168\n" +
            "acc +22\n" +
            "nop +561\n" +
            "jmp -26\n" +
            "jmp +1\n" +
            "acc -7\n" +
            "jmp -5\n" +
            "acc +28\n" +
            "acc -6\n" +
            "jmp +370\n" +
            "jmp +94\n" +
            "acc +50\n" +
            "acc +42\n" +
            "acc -9\n" +
            "acc +30\n" +
            "jmp +70\n" +
            "acc +29\n" +
            "jmp +166\n" +
            "acc -5\n" +
            "acc -18\n" +
            "nop +84\n" +
            "acc +2\n" +
            "jmp +366\n" +
            "jmp -40\n" +
            "acc -4\n" +
            "acc -15\n" +
            "acc -1\n" +
            "jmp +169\n" +
            "jmp +1\n" +
            "acc -4\n" +
            "acc +0\n" +
            "jmp -45\n" +
            "nop -21\n" +
            "nop +241\n" +
            "acc -18\n" +
            "acc +19\n" +
            "jmp +26\n" +
            "nop -51\n" +
            "jmp +260\n" +
            "acc +17\n" +
            "jmp +428\n" +
            "acc +6\n" +
            "jmp +405\n" +
            "acc +22\n" +
            "acc +10\n" +
            "nop +471\n" +
            "jmp +352\n" +
            "acc -6\n" +
            "acc +48\n" +
            "acc +7\n" +
            "acc +3\n" +
            "jmp +57\n" +
            "acc -10\n" +
            "acc +16\n" +
            "acc +16\n" +
            "acc +43\n" +
            "jmp +432\n" +
            "acc -5\n" +
            "acc +0\n" +
            "nop +339\n" +
            "acc +49\n" +
            "jmp +17\n" +
            "acc +33\n" +
            "nop +166\n" +
            "acc -5\n" +
            "jmp +392\n" +
            "nop +246\n" +
            "acc -7\n" +
            "acc +21\n" +
            "acc +30\n" +
            "jmp +398\n" +
            "acc +36\n" +
            "acc +24\n" +
            "acc -15\n" +
            "acc -9\n" +
            "jmp +114\n" +
            "acc +19\n" +
            "jmp +11\n" +
            "acc +43\n" +
            "nop +182\n" +
            "jmp -129\n" +
            "nop -29\n" +
            "acc -6\n" +
            "acc +2\n" +
            "jmp +398\n" +
            "jmp +78\n" +
            "acc +36\n" +
            "jmp +393\n" +
            "acc +15\n" +
            "nop -11\n" +
            "acc -7\n" +
            "acc -9\n" +
            "jmp +76\n" +
            "acc +0\n" +
            "acc +27\n" +
            "jmp +25\n" +
            "acc +27\n" +
            "nop -54\n" +
            "jmp +458\n" +
            "acc +3\n" +
            "acc +29\n" +
            "acc -4\n" +
            "acc +43\n" +
            "jmp +413\n" +
            "acc +33\n" +
            "acc +13\n" +
            "jmp +382\n" +
            "jmp -83\n" +
            "acc +42\n" +
            "acc +24\n" +
            "jmp +64\n" +
            "acc +23\n" +
            "acc -13\n" +
            "nop +110\n" +
            "acc -5\n" +
            "jmp +114\n" +
            "jmp +113\n" +
            "nop +112\n" +
            "acc +26\n" +
            "jmp -133\n" +
            "jmp -12\n" +
            "jmp +1\n" +
            "jmp +330\n" +
            "acc +25\n" +
            "acc -1\n" +
            "acc +30\n" +
            "acc +42\n" +
            "jmp -187\n" +
            "jmp +1\n" +
            "acc +20\n" +
            "acc +35\n" +
            "acc +36\n" +
            "jmp -125\n" +
            "jmp +165\n" +
            "acc +28\n" +
            "acc -17\n" +
            "acc -12\n" +
            "jmp +1\n" +
            "jmp -120\n" +
            "nop +1\n" +
            "acc +2\n" +
            "acc +26\n" +
            "jmp +398\n" +
            "acc +20\n" +
            "acc -1\n" +
            "jmp -127\n" +
            "acc +36\n" +
            "acc +14\n" +
            "jmp +1\n" +
            "jmp +331\n" +
            "acc +50\n" +
            "acc +1\n" +
            "acc -10\n" +
            "nop +159\n" +
            "jmp -83\n" +
            "jmp +374\n" +
            "acc +17\n" +
            "jmp +372\n" +
            "acc +44\n" +
            "nop -39\n" +
            "jmp +228\n" +
            "acc +17\n" +
            "jmp +74\n" +
            "acc +16\n" +
            "acc +33\n" +
            "acc -2\n" +
            "jmp +152\n" +
            "jmp +29\n" +
            "acc +8\n" +
            "acc +27\n" +
            "nop +59\n" +
            "jmp -32\n" +
            "acc +28\n" +
            "jmp -227\n" +
            "nop -35\n" +
            "jmp -168\n" +
            "acc +13\n" +
            "nop +390\n" +
            "jmp -204\n" +
            "acc +16\n" +
            "acc +44\n" +
            "jmp -230\n" +
            "jmp +25\n" +
            "acc +30\n" +
            "jmp +383\n" +
            "acc -11\n" +
            "acc +38\n" +
            "acc +11\n" +
            "jmp +341\n" +
            "acc +35\n" +
            "acc +46\n" +
            "acc -1\n" +
            "jmp +94\n" +
            "acc -4\n" +
            "acc +12\n" +
            "jmp +111\n" +
            "jmp +133\n" +
            "nop +283\n" +
            "acc +13\n" +
            "acc +37\n" +
            "jmp +74\n" +
            "nop -218\n" +
            "jmp -178\n" +
            "acc +46\n" +
            "acc +25\n" +
            "acc -5\n" +
            "jmp -174\n" +
            "acc +28\n" +
            "acc +39\n" +
            "acc +36\n" +
            "acc +22\n" +
            "jmp -172\n" +
            "acc +19\n" +
            "jmp -250\n" +
            "nop +62\n" +
            "acc +44\n" +
            "nop +347\n" +
            "acc +40\n" +
            "jmp +345\n" +
            "acc -3\n" +
            "acc -13\n" +
            "acc -11\n" +
            "jmp +56\n" +
            "jmp -180\n" +
            "acc +17\n" +
            "acc -4\n" +
            "acc +46\n" +
            "nop -165\n" +
            "jmp +321\n" +
            "acc -4\n" +
            "jmp +1\n" +
            "acc +9\n" +
            "acc -12\n" +
            "jmp -155\n" +
            "acc +5\n" +
            "jmp -96\n" +
            "acc +0\n" +
            "acc -2\n" +
            "acc +38\n" +
            "jmp +67\n" +
            "acc -4\n" +
            "nop -283\n" +
            "acc +28\n" +
            "jmp +324\n" +
            "acc -9\n" +
            "acc +43\n" +
            "acc -1\n" +
            "acc +9\n" +
            "jmp -290\n" +
            "acc +3\n" +
            "acc +22\n" +
            "nop +84\n" +
            "acc -17\n" +
            "jmp -210\n" +
            "acc +7\n" +
            "jmp -260\n" +
            "nop -232\n" +
            "nop +87\n" +
            "acc +43\n" +
            "acc +36\n" +
            "jmp +96\n" +
            "jmp +238\n" +
            "acc +13\n" +
            "acc -14\n" +
            "acc +32\n" +
            "acc +11\n" +
            "jmp -146\n" +
            "acc +13\n" +
            "acc +37\n" +
            "acc -10\n" +
            "jmp +187\n" +
            "acc +49\n" +
            "acc +15\n" +
            "jmp -234\n" +
            "jmp -328\n" +
            "jmp -136\n" +
            "jmp +143\n" +
            "jmp +1\n" +
            "acc +27\n" +
            "acc +22\n" +
            "jmp +1\n" +
            "jmp -5\n" +
            "acc +30\n" +
            "nop -7\n" +
            "acc -6\n" +
            "jmp -71\n" +
            "acc -17\n" +
            "acc +15\n" +
            "jmp -52\n" +
            "jmp -126\n" +
            "acc -4\n" +
            "jmp +151\n" +
            "jmp +52\n" +
            "nop -86\n" +
            "acc +25\n" +
            "jmp +187\n" +
            "nop -22\n" +
            "jmp -219\n" +
            "acc +33\n" +
            "nop -120\n" +
            "acc +0\n" +
            "jmp +215\n" +
            "acc +46\n" +
            "acc +38\n" +
            "jmp +1\n" +
            "jmp -262\n" +
            "jmp +157\n" +
            "acc -15\n" +
            "acc +48\n" +
            "acc +39\n" +
            "acc +10\n" +
            "jmp -137\n" +
            "acc +47\n" +
            "acc +50\n" +
            "jmp -324\n" +
            "nop +214\n" +
            "acc +39\n" +
            "jmp -178\n" +
            "acc +49\n" +
            "acc -10\n" +
            "jmp -268\n" +
            "jmp +50\n" +
            "acc -14\n" +
            "nop -100\n" +
            "jmp +20\n" +
            "acc +45\n" +
            "acc -12\n" +
            "acc -4\n" +
            "jmp -208\n" +
            "acc -19\n" +
            "jmp -340\n" +
            "acc +36\n" +
            "nop -358\n" +
            "acc +5\n" +
            "jmp -348\n" +
            "acc +47\n" +
            "nop -18\n" +
            "acc -12\n" +
            "jmp -131\n" +
            "acc +19\n" +
            "acc +10\n" +
            "acc +19\n" +
            "acc +31\n" +
            "jmp -164\n" +
            "nop +162\n" +
            "nop -260\n" +
            "jmp +146\n" +
            "acc +32\n" +
            "acc -1\n" +
            "nop -14\n" +
            "jmp -192\n" +
            "acc +3\n" +
            "acc +31\n" +
            "nop -185\n" +
            "jmp -208\n" +
            "jmp -69\n" +
            "acc +43\n" +
            "acc +43\n" +
            "jmp -68\n" +
            "acc -16\n" +
            "acc +5\n" +
            "acc -9\n" +
            "jmp +126\n" +
            "acc +33\n" +
            "acc +2\n" +
            "acc +34\n" +
            "acc -9\n" +
            "jmp -16\n" +
            "acc +34\n" +
            "acc -19\n" +
            "jmp -266\n" +
            "nop +135\n" +
            "nop -389\n" +
            "acc +33\n" +
            "jmp -195\n" +
            "acc +48\n" +
            "jmp +1\n" +
            "acc -12\n" +
            "jmp +143\n" +
            "nop -317\n" +
            "acc -14\n" +
            "nop -127\n" +
            "acc +32\n" +
            "jmp -372\n" +
            "acc +24\n" +
            "nop -41\n" +
            "nop -42\n" +
            "jmp -344\n" +
            "acc +23\n" +
            "nop +117\n" +
            "nop +92\n" +
            "acc +42\n" +
            "jmp +143\n" +
            "acc +48\n" +
            "acc -6\n" +
            "nop -272\n" +
            "acc -13\n" +
            "jmp -379\n" +
            "acc -2\n" +
            "acc +44\n" +
            "acc +9\n" +
            "jmp -369\n" +
            "acc +6\n" +
            "acc +25\n" +
            "acc +34\n" +
            "jmp -301\n" +
            "nop -227\n" +
            "acc +43\n" +
            "jmp -141\n" +
            "acc +12\n" +
            "acc +41\n" +
            "acc +17\n" +
            "acc -11\n" +
            "jmp +29\n" +
            "jmp -121\n" +
            "acc +6\n" +
            "acc +7\n" +
            "acc +7\n" +
            "jmp +131\n" +
            "nop +144\n" +
            "nop -142\n" +
            "acc -13\n" +
            "acc -18\n" +
            "jmp +149\n" +
            "acc +14\n" +
            "acc +49\n" +
            "acc +25\n" +
            "acc -17\n" +
            "jmp -9\n" +
            "acc +26\n" +
            "acc -4\n" +
            "jmp -230\n" +
            "acc -18\n" +
            "acc +36\n" +
            "acc +27\n" +
            "nop -142\n" +
            "jmp +21\n" +
            "acc +34\n" +
            "nop +54\n" +
            "jmp -476\n" +
            "acc +10\n" +
            "jmp -174\n" +
            "nop -354\n" +
            "acc +1\n" +
            "jmp -324\n" +
            "acc +40\n" +
            "jmp +94\n" +
            "acc -12\n" +
            "jmp -136\n" +
            "nop -454\n" +
            "acc -14\n" +
            "jmp +116\n" +
            "acc +12\n" +
            "acc -1\n" +
            "nop -453\n" +
            "jmp -241\n" +
            "jmp -479\n" +
            "acc -19\n" +
            "jmp -87\n" +
            "acc +27\n" +
            "acc +48\n" +
            "acc +0\n" +
            "jmp -476\n" +
            "acc +16\n" +
            "acc +46\n" +
            "jmp -534\n" +
            "acc +0\n" +
            "jmp -344\n" +
            "acc +0\n" +
            "acc +28\n" +
            "jmp +10\n" +
            "jmp -248\n" +
            "nop -186\n" +
            "jmp +1\n" +
            "acc +26\n" +
            "jmp -153\n" +
            "acc +14\n" +
            "acc -8\n" +
            "nop -416\n" +
            "jmp -91\n" +
            "jmp -409\n" +
            "jmp -326\n" +
            "acc +2\n" +
            "acc +8\n" +
            "acc -18\n" +
            "acc +33\n" +
            "jmp -468\n" +
            "jmp -175\n" +
            "acc -7\n" +
            "acc +45\n" +
            "jmp -18\n" +
            "jmp -375\n" +
            "acc -8\n" +
            "jmp +28\n" +
            "acc -16\n" +
            "nop -38\n" +
            "acc +37\n" +
            "acc +48\n" +
            "jmp -343\n" +
            "acc +10\n" +
            "acc +26\n" +
            "acc -9\n" +
            "acc -16\n" +
            "jmp -348\n" +
            "acc +37\n" +
            "jmp -453\n" +
            "acc -2\n" +
            "acc +27\n" +
            "acc +17\n" +
            "acc +28\n" +
            "jmp -406\n" +
            "acc +25\n" +
            "acc +24\n" +
            "acc +44\n" +
            "acc +44\n" +
            "jmp -532\n" +
            "acc +10\n" +
            "jmp -531\n" +
            "acc +39\n" +
            "acc +40\n" +
            "jmp -284\n" +
            "acc +19\n" +
            "acc +3\n" +
            "nop -533\n" +
            "acc -3\n" +
            "jmp -162\n" +
            "nop -438\n" +
            "acc -5\n" +
            "jmp -114\n" +
            "acc +45\n" +
            "acc +1\n" +
            "acc +28\n" +
            "acc +9\n" +
            "jmp -550\n" +
            "jmp -222\n" +
            "jmp -106\n" +
            "acc -7\n" +
            "nop -263\n" +
            "nop -375\n" +
            "jmp -381\n" +
            "acc -4\n" +
            "nop -223\n" +
            "jmp -171\n" +
            "jmp -465\n" +
            "acc -2\n" +
            "nop -562\n" +
            "jmp -190\n" +
            "acc +40\n" +
            "jmp -4\n" +
            "acc +30\n" +
            "acc +21\n" +
            "jmp -435\n" +
            "acc +1\n" +
            "acc +10\n" +
            "jmp +1\n" +
            "jmp -157\n" +
            "acc -7\n" +
            "acc +18\n" +
            "acc -3\n" +
            "acc +24\n" +
            "jmp -113\n" +
            "acc +21\n" +
            "jmp -339\n" +
            "acc +34\n" +
            "jmp -563\n" +
            "acc +27\n" +
            "jmp -589\n" +
            "jmp -61\n" +
            "acc +35\n" +
            "acc +50\n" +
            "acc +8\n" +
            "jmp -553\n" +
            "acc +48\n" +
            "acc -15\n" +
            "acc +29\n" +
            "acc +24\n" +
            "jmp +1";
}
